/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "secondary-fixed": "#e9ddff",
            "on-tertiary-container": "#006d4a",
            "on-surface-variant": "#b9cacb",
            "on-error": "#690005",
            "surface": "#0b1326",
            "secondary-fixed-dim": "#d0bcff",
            "on-secondary-fixed": "#23005c",
            "surface-container-lowest": "#060e20",
            "surface-bright": "#31394d",
            "on-primary-fixed": "#002022",
            "on-tertiary-fixed": "#002113",
            "surface-container": "#171f33",
            "primary-fixed": "#7df4ff",
            "outline-variant": "#3b494b",
            "error": "#ffb4ab",
            "on-primary": "#00363a",
            "tertiary-container": "#65f2b5",
            "surface-container-low": "#131b2e",
            "tertiary": "#d8ffe7",
            "surface-container-high": "#222a3d",
            "primary-fixed-dim": "#00dbe9",
            "primary": "#dbfcff",
            "on-primary-container": "#006970",
            "surface-tint": "#00dbe9",
            "on-secondary": "#3c0091",
            "inverse-surface": "#dae2fd",
            "secondary": "#d0bcff",
            "error-container": "#93000a",
            "surface-variant": "#2d3449",
            "on-tertiary": "#003824",
            "inverse-on-surface": "#283044",
            "on-tertiary-fixed-variant": "#005236",
            "on-background": "#dae2fd",
            "on-error-container": "#ffdad6",
            "on-surface": "#dae2fd",
            "tertiary-fixed": "#6ffbbe",
            "on-secondary-container": "#c4abff",
            "surface-container-highest": "#2d3449",
            "surface-dim": "#0b1326",
            "secondary-container": "#571bc1",
            "on-primary-fixed-variant": "#004f54",
            "tertiary-fixed-dim": "#4edea3",
            "primary-container": "#00f0ff",
            "background": "#0b1326",
            "on-secondary-fixed-variant": "#5516be",
            "outline": "#849495",
            "inverse-primary": "#006970"
        },
        "borderRadius": {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
        },
        "spacing": {
            "sm": "16px",
            "xl": "64px",
            "margin-mobile": "16px",
            "base": "4px",
            "md": "24px",
            "margin-desktop": "32px",
            "xs": "8px",
            "gutter": "20px",
            "lg": "40px"
        },
        "fontFamily": {
            "headline-lg-mobile": ["Sora"],
            "headline-lg": ["Sora"],
            "body-md": ["Inter"],
            "label-sm": ["JetBrains Mono"],
            "display-lg": ["Sora"],
            "sans": ["Inter", "sans-serif"]
        },
        "fontSize": {
            "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
            "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
            "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
            "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
        }
    },
  },
  plugins: [],
}
